feature: S3C-3669 bucket encryption design
scality/citadel pull request #43
Opened 2021-04-19 21:32 UTC by jonathan-gramain

Add a design document for the bucket encryption API support (bucket
and object-level).

2021-04-20 00:28 UTC, terrydervaux commented on docs/design/bucket-encryption.md
> +**TODO**: determine if they are needed. They can prevent from changing
As discussed on slack, we can remove bucket policies from our plan because our customers only want to prevent unencrypted objects in buckets.

2021-04-21 19:59 UTC, tmacro reviewed
Might be worth it to include some examples of the `serverSideEncryption` section under a dedicated heading to directly show how the different "modes" effect the MD.

2021-04-21 19:59 UTC, tmacro approved these changes

2021-04-21 20:51 UTC, jonathan-gramain commented
@tmacro I reworked the internal bucket metadata section to contain separate examples for each case, it should be clearer (plus extra info on the API implementation too)

2021-04-22 16:52 UTC, tmacro approved these changes
Looks good, the various modes are much more clear now.

2021-04-22 16:52 UTC, tmacro commented on docs/design/bucket-encryption.md
> +than in section [Default Encryption Configuration With "AES256"
```suggestion
as in the section [Default Encryption Configuration With "AES256"
```

2021-04-22 16:52 UTC, tmacro commented on docs/design/bucket-encryption.md
> +This way, we can treat is in the same way, simplifying the logic and
```suggestion
This way, we can treat it in the same way, simplifying the logic and
```

2021-04-22 17:50 UTC, jonathan-gramain commented on docs/design/bucket-encryption.md
> +   ...
Yes sounds good to me

2021-04-22 17:52 UTC, jonathan-gramain commented on docs/design/bucket-encryption.md
> +   ...
Maybe the code already checks this, but it should then return an error if there are multiple rules.

2021-04-28 18:53 UTC, tmacro commented on docs/design/bucket-encryption.md
> +         <SSEAlgorithm>aws:kms</SSEAlgorithm>
I just discovered AWS allows a PutBucketEncryption with algo `aws:kms` and no specified `KMSMasterKeyID`. a subsequent GetBucketEncryption does not return a key id either.

2021-04-28 20:35 UTC, jonathan-gramain commented on docs/design/bucket-encryption.md
> +         <SSEAlgorithm>aws:kms</SSEAlgorithm>
Yes, so we need to condition `aws:kms` **and** key provided in order to use a configured key and return it via GetBucketEncryption, correct? otherwise it's equivalent to AES256.

2021-04-28 22:11 UTC, tmacro commented on docs/design/bucket-encryption.md
> +         <SSEAlgorithm>aws:kms</SSEAlgorithm>
Yes, I imagine it effects billing on AWS, but for our use its the same.

2021-05-07 16:54 UTC, terrydervaux approved these changes
It's super clear. Thanks @jonathan-gramain .

We will need to add in this design document how we manage the S3C configuration(federation) when S3C needs to be integrated with a multi-nodes KMS. It will be in another PR(S3C-4362).

2021-05-10 09:47 UTC, scality-gdoumergue requested changes
Some details to be added.
I would also like to make KMS configuration easier. Today we have to download a .properties file and upload it into Federation. I think it'd be cool to have it directly integrated as a template, with a new Ansible variable set. Do you think it's feasible to add it to this design doc?

2021-05-10 09:47 UTC, scality-gdoumergue commented on docs/design/bucket-encryption.md
> +### PutBucketEncryption
Do we already implement the BucketKeyEnabled rule? We should explicitely tell it in this doc.

2021-05-10 09:47 UTC, scality-gdoumergue commented on docs/design/bucket-encryption.md
> +  for testing), and key IDs look different with a real KMS server.
Are we sure it won't break any compatibility with S3 clients?

2021-05-10 09:47 UTC, scality-gdoumergue commented on docs/design/bucket-encryption.md
> +We currently do not plan to support bucket policies related to encryption.
Can you specify the name of the related conditions? 
I guess it's:
- s3:x-amz-server-side-encryption
- s3:x-amz-server-side-encryption-aws-kms-key-id

2021-05-10 23:29 UTC, jonathan-gramain commented on docs/design/bucket-encryption.md
> +  for testing), and key IDs look different with a real KMS server.
I don't know about this, but this part will be unchanged compared to what already exists, so assuming clients work with the current scheme, they should still work with the new API support.

If it indeed does break the compatibility for certain clients that we would not have seen yet, it's a new issue and the best would be to tackle it as a separate bug ticket.

2021-05-10 23:35 UTC, jonathan-gramain commented on docs/design/bucket-encryption.md
> +We currently do not plan to support bucket policies related to encryption.
Yes, or only `s3:x-amz-server-side-encryption` should be enough for the purpose, I will add a precision.

2021-05-20 07:38 UTC, scality-gdoumergue commented on docs/design/bucket-encryption.md
> +  encrypted with the master key
Does it mean that, during the object's download, S3C doesn't need to contact the KMS server to decrypt the object?

2021-05-20 20:05 UTC, scality-gdoumergue approved these changes

2021-05-20 20:15 UTC, jonathan-gramain commented
/approve

2021-05-20 20:16 UTC, merged