test: S3C-4409 initial draft of bucket encryption test plan
scality/citadel pull request #49
Opened 2021-05-27 01:35 UTC by jonathan-gramain

- a deployment test with Federation

- a functional test to check encryption correctness

- a set of performance tests with cosbench to execute on a perf lab

This was inspired from https://github.com/scality/artesca/blob/development/1.0/docs/developer/test-plan/data-services.rst, ty @RachedBenMustapha !

2021-06-02 18:31 UTC, tmacro approved these changes

2021-07-01 21:02 UTC, scality-gdoumergue requested changes

2021-07-01 21:02 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
We should configure the gemalto plugin to log into its own log file (/logs/gemalto.log). This can help us know that everything works fine.

2021-07-02 15:51 UTC, scality-gdoumergue requested changes

2021-07-02 15:51 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +#### Expected Results
Add an upgrade section.
- Install S3C 7.9
- Create an encrypted bucket the old way
- Upgrade to 7.10
- Encryption must still work for the old bucket.

2021-07-05 07:39 UTC, scality-gdoumergue requested changes

2021-07-05 07:39 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
+ Check on Ciphertrust web page that the s3-encrypted-bucket-1 key has been created.

2021-07-05 07:39 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
Delete the objects, remove the bucket. The s3-encrypted-bucket-1 key on Ciphertrust should be removed as well.

2021-07-09 01:41 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
> Check on Ciphertrust web page that the s3-encrypted-bucket-1 key has been created.

Good idea. In practice I see that the keys are named with random strings that are stored in bucket metadata, like `ks-abcdef....`. So it's possible to check that the matching key exist from the bucket metadata, with a lookup of bucket metadata first.

2021-07-09 01:41 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
The set of operations happening inside the KMS look rather obscure for now, but ideally we should be able to "decipher" what's going on. I'll just mention that there should be no error.

2021-07-09 01:41 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
The bucket creation is expected to fail, added a test for that

2021-07-12 20:27 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
Is it possible now or does it require code changes?

2021-07-13 17:13 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
No code change required. Add these config lines in ProtectAppICAPI.properties:

Log_File=/logs/gemalto.log
Log_Level=HIGH

2021-07-13 17:31 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
Add a section to test KMS on versioned buckets.

2021-07-15 08:18 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
Add a section to test encryption-related IAM authorization:

- The root user can always use the bucket-encryption related actions,
- An IAM user can not use the bucket-encryption related actions,
- An IAM user with the proper policy should be able to use the bucket-encryption related actions,
- Least-privilege must be enforced. If a user i attached to a policy that explicitely forbids the use of bucket-encryption related actions, another policy shouldn't be able to allow them.

2021-07-20 00:00 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
Added a versioned bucket as a new test case in this test

2021-07-20 00:39 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
Added the first three points.

For the fourth one, what kind of other policy that could allow the encryption actions are you referring to, bucket policies? IAM group policies? I know IAM has the notion of "Deny" policies for that, although I'm not familiar enough with their use to be comfortable describing how to set them in the right context, so help would be appreciated.

2021-07-20 00:41 UTC, jonathan-gramain commented
@scality-gdoumergue could you please review the latest changes? If good for you I'd like to merge this during this sprint (so this week).

Thanks!

2021-07-29 00:01 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
I realized that the ProtectApplCAPI.properties file seems to be used only when we setup the scality KMS with the NAE protocol, where the "scality-kms" container is used.

I did not test the NAE mode, only KMIP, and I understood from the PO that we were going to deprecate NAE and going to focus on KMIP only, hence we can probably drop this.

I believe the logging is configured directly in the Thales CipherTrust GUI when using KMIP.

I am not sure I understand fully how it is supposed to be configured, so please correct me if I'm wrong.

2021-07-29 00:03 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
I will remove the section that I added about logging then

2021-07-29 20:05 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +### Deployment through Federation
@scality-gdoumergue the deployment section was previously referring to how to deploy the "kms" (NAE) protocol, which we want to deprecate as I explained for the logging. I think there exists some documentation for kmip deployment but I could not find it. For now I added the steps that I took to deploy and configure the CipherTrust VM on the lab, but ideally we should have an up-to-date link on how to configure with KMIP.

2021-07-30 10:12 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
@jonathan-gramain I don't understand.
- Deprecating NAE: what about the customers who already use NAE?
- Do you mean going full KMIP we don't need the code from the scality-kms container?

2021-07-30 10:21 UTC, scality-gdoumergue commented on docs/test-plan/bucket-encryption.md
> +
Create an IAM policy with:

`"Action":["s3:PutEncryptionConfiguration"],"Effect":"Deny"`

And a second one with:

`"Action":["s3:PutEncryptionConfiguration"],"Effect":"Allow"`

Attach the two policies to a single IAM user.

The user shouldn't be able to `aws s3api put-bucket-encryption`.

2021-07-30 17:58 UTC, jonathan-gramain commented on docs/test-plan/bucket-encryption.md
> +
> Deprecating NAE: what about the customers who already use NAE?

I believe it should still work as it used to, just that we are not focusing on testing it, we are focusing on KMIP.

> Do you mean going full KMIP we don't need the code from the scality-kms container?

Yes, that's correct, KMIP does not require the scality-kms container.

2021-07-30 19:48 UTC, scality-gdoumergue approved these changes

2021-07-30 20:01 UTC, jonathan-gramain commented
/approve

2021-07-30 20:02 UTC, merged