ft(UTAPI-2): Update utapi design to improve performance and disk usage
scality/citadel pull request #54
Opened 2021-07-29 18:03 UTC by tmacro

2021-07-29 18:41 UTC, mrepop approved these changes

2021-07-29 20:43 UTC, saitharunthodupunuru approved these changes

2021-07-29 20:51 UTC, anurag4DSB approved these changes

2021-07-30 15:22 UTC, vrancurel requested changes

2021-07-30 15:22 UTC, vrancurel commented on docs/design/utapi.md
> +holding the same values.
It would clearer to provide an example where it is not the same value for snapshots ? e.g. with a previous state for the bck's and acc.

2021-07-30 15:22 UTC, vrancurel commented on docs/design/utapi.md
> +creation to create the various levels of metrics.
1. That would be really nice not to pollute the global redis-local namespace (because it is used in other components) and as we saw on the field, there are sometimes millions of keys in the global namespace.

2. Also I would suggest to directly write the events in the shards, because I don't see the value of writing them first and then referencing them in the shards.

Hopefully implementing 2. will automatically solve 1.

2021-07-30 15:22 UTC, vrancurel commented on docs/design/utapi.md
> +-->
We need to add a section on how we can guarantee the results are accurate to a pre-defined granularity:

1. we shall somehow indicate that a result is *transient*, e.g. if we query Utapi "live" result, it is very likely that the datalogs haven't propagated yet and the result is wrong.
2. we shall have a mode to query from a safe point, e.g. the last checkpoint. If we can evaluate the propagation time of the datalog, we can be sure that the result in the last checkpoint is safe. Similarly if we detect that the lag is greater than the last checkpoint, then we must return that somehow the result in "unsafe".

Please specify how we can achieve the 2 above points.

2021-07-30 15:48 UTC, cmrh approved these changes

2021-07-30 16:26 UTC, tmacro commented on docs/design/utapi.md
> +Utapi stores a protobuf object using Warp 10's binary data type containing
Only the checkpoints are stored. I meant for `operation` to refer to checkpoints, but it doesn't convey that very well.

2021-07-30 18:23 UTC, vrancurel commented on docs/design/utapi.md
> +-->
So each stateful node can emit regularly a "canary". We can use this "canary" to determine the "freshness" of the result.

2021-08-03 13:55 UTC, vrancurel commented on docs/design/utapi.md
> +-->
So the canary must be emitted by the stateful nodes every 15mn by default (tunable). A manual request could then establish the staleness or the lag of the datalog replication.

For data loss detection. When a Cloudserver cannot write any more to redis-local it emits a 'potential_dataloss' event directly to Warp10, then cache in its RAM. When it cannot write any more in its RAM it writes a 'dataloss' event directly to Warp10. A manual request could then detect data loss if a 'dataloss' or a 'potential_dataloss' event is not followed by a 'reindex'.

2021-08-03 17:10 UTC, tmacro commented on docs/design/utapi.md
> +-->
I suggest adding a 3rd event to be published if the cache has successfully been flushed and no events are lost. We can use this to avoid reducing confidence in the results if no data have actually been lost.

2021-08-18 17:19 UTC, vrancurel approved these changes

2021-08-18 17:45 UTC, merged